#!/usr/bin/env python3
"""views.py - regenerate the two fleet-wide views (V2): index.md (a roll-call
table over every manifest) and workstream-graph.md (a mermaid lineage
picture). Ported from cos 0.20.0's workstream-index.py + workstream-graph.py,
config-driven (no "staff/cos" literal), consolidated behind ONE discovery
function (workstream_lib.discover_manifests/find_problems - V4).

Called by every lifecycle verb after it writes a manifest (V2: "regenerate
at the end of any verb that writes a manifest, and on demand from list/
graph; no Stop hook, no Ballast hook" - a manifest changes only through a
verb, so verb-triggered regen can never go stale). This script is the
`regen` primitive those verbs shell out to (or import directly).

CLI:
    views.py regen [--root PATH]
        -> writes <state_root>/index.md and <state_root>/workstream-graph.md,
           prints a one-line summary; exit 0 on success, 1 on a real
           write failure. Read-only otherwise (never touches disk on a
           discovery/render error - those degrade into the anomaly
           sections themselves).
"""
import argparse
import datetime
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import workstream_lib as wslib

CELL_CAP = 160


def _cell(value):
    if not isinstance(value, str) or not value.strip():
        return "—"   # em dash
    s = " ".join(value.split())
    if len(s) > CELL_CAP:
        s = s[:CELL_CAP - 1].rstrip() + "…"
    return s.replace("|", "/").replace("<", "\\<").replace(">", "\\>")


def render_index(manifests, orphans, problems):
    lines = [
        "<!-- GENERATED by workstream:views regen - do not hand-edit -->",
        "# Workstreams - index - %s" % datetime.date.today().isoformat(),
        "",
        "| dir | name | state | focus | projects | reports to | collaborates with | absorbed |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for dirname in sorted(manifests):
        m = manifests[dirname]
        raw_projects = m.get("projects")
        proj_ids = ([p.strip() for p in raw_projects if isinstance(p, str) and p.strip()]
                   if isinstance(raw_projects, list) else [])
        proj_col = ", ".join(_cell(p) for p in proj_ids) if proj_ids else "—"

        report_entry = wslib.normalize_direct_report(m)
        if report_entry is None:
            reports_col = "—"
        else:
            disp_name, target_state = wslib.resolve_ref_display(report_entry, manifests)
            reports_col = "—" if disp_name is None else _cell(disp_name)
            if target_state in ("closed", "absorbed"):
                reports_col += " [%s]" % target_state

        collab_cells = []
        for e in wslib.normalize_collaborate(m):
            disp_name, target_state = wslib.resolve_ref_display(e, manifests)
            if disp_name is None:
                continue
            cell = _cell(disp_name)
            if target_state in ("closed", "absorbed"):
                cell += " [%s]" % target_state
            scope = e.get("scope")
            if isinstance(scope, str) and scope.strip():
                cell += " (%s)" % _cell(scope)
            collab_cells.append(cell)
        collaborate_col = ", ".join(collab_cells) if collab_cells else "—"

        absorbed_cells = [_cell(e.get("name") or e.get("born_session"))
                         for e in wslib.normalize_absorbed(m)]
        absorbed_col = ", ".join(absorbed_cells) if absorbed_cells else "—"

        lines.append("| `%s` | %s | %s | %s | %s | %s | %s | %s |"
                     % (dirname, _cell(m.get("name")), _cell(m.get("state")),
                        _cell(m.get("focus")), proj_col, reports_col, collaborate_col,
                        absorbed_col))
    if not manifests:
        lines.append("| _none_ | | | | | | | |")
    lines.append("")

    if orphans:
        lines.append("## Orphan dirs (no valid manifest - flag-only, never auto-removed)")
        lines.append("")
        for dirname, reason in orphans:
            lines.append("- `%s` - %s" % (dirname, reason))
        lines.append("")

    if problems:
        lines.append("## Manifest anomalies (flag-only, never auto-fixed)")
        lines.append("")
        for kind, detail in problems:
            lines.append("- **%s** - %s" % (kind, detail))
        lines.append("")

    return "\n".join(lines)


_STATE_CLASS = {"active": "active", "closed": "closed", "absorbed": "absorbed"}


def _mermaid_label(s):
    return " ".join(str(s).split()).replace('"', "'")


def render_graph(manifests):
    """A mermaid flowchart: one node per manifest (colored by state), plus
    a dimmed ghost node per previous_names entry (rename history). Five
    edge kinds, each a visually distinct arrow style: spawned_from (solid),
    direct_report (bold), collaborate (dashed, scope in the label),
    absorbed_by (dotted), rename (thin dotted, from the ghost). Simplified
    from workstream-graph.py's per-index linkStyle scheme to per-kind
    arrow syntax - functionally equivalent edge-type distinction, lighter
    to generate and to read (documented simplification, 04i residual)."""
    lines = ["```mermaid", "flowchart TD",
            'classDef active fill:#cfe2ff,stroke:#0a58ca,color:#052c65;',
            'classDef closed fill:#d1e7dd,stroke:#146c43,color:#0a3622;',
            'classDef absorbed fill:#e2e3e5,stroke:#6c757d,color:#41464b,stroke-dasharray:4 2;',
            'classDef ghost fill:#f8f9fa,stroke:#adb5bd,color:#adb5bd,stroke-dasharray:2 2;',
            'classDef unknownstate fill:#fff3cd,stroke:#997404,color:#664d03;']

    for born in sorted(manifests):
        m = manifests[born]
        name = m.get("name") or born
        state = m.get("state")
        css = _STATE_CLASS.get(state, "unknownstate")
        lines.append('n_%s["%s"]:::%s' % (born.replace("-", "_"), _mermaid_label(name), css))

    ghost_counter = 0
    ghost_ids = {}
    for born in sorted(manifests):
        m = manifests[born]
        prev = m.get("previous_names")
        if not isinstance(prev, list):
            continue
        for entry in prev:
            if not isinstance(entry, dict):
                continue
            old_name = entry.get("name")
            if not (isinstance(old_name, str) and old_name.strip()):
                continue
            ghost_counter += 1
            gid = "g_%d" % ghost_counter
            ghost_ids[(born, ghost_counter)] = gid
            lines.append('%s["%s (former name)"]:::ghost' % (gid, _mermaid_label(old_name)))
            lines.append('%s -.->|renamed| n_%s' % (gid, born.replace("-", "_")))

    for born in sorted(manifests):
        m = manifests[born]
        nid = "n_%s" % born.replace("-", "_")

        sfs = m.get("spawned_from_session")
        if isinstance(sfs, str) and sfs.strip() and sfs in manifests:
            lines.append('n_%s --> %s' % (sfs.replace("-", "_"), nid))

        report_entry = wslib.normalize_direct_report(m)
        if report_entry is not None:
            sess = report_entry.get("session")
            if isinstance(sess, str) and sess.strip() and sess in manifests:
                lines.append('%s ==>|reports to| n_%s' % (nid, sess.replace("-", "_")))

        for e in wslib.normalize_collaborate(m):
            sess = e.get("session")
            if isinstance(sess, str) and sess.strip() and sess in manifests and sess > born:
                # draw once per reciprocal pair (sess > born breaks the tie)
                scope = e.get("scope")
                label = "collaborates" + (": %s" % _mermaid_label(scope) if isinstance(scope, str) and scope.strip() else "")
                lines.append('%s -.->|%s| n_%s' % (nid, label, sess.replace("-", "_")))

        abs_s = m.get("absorbed_by_session")
        if isinstance(abs_s, str) and abs_s.strip() and abs_s in manifests:
            lines.append('%s -..->|absorbed by| n_%s' % (nid, abs_s.replace("-", "_")))

    lines.append("```")
    return "\n".join(lines)


def render_graph_markdown(manifests):
    header = [
        "<!-- GENERATED by workstream:views regen - do not hand-edit -->",
        "# Workstream graph - %s" % datetime.date.today().isoformat(),
        "",
        "Edge key: solid = forked from (spawned_from) - bold = reports to "
        "(direct_report) - dashed = collaborates with (collaborate, scope "
        "in the label) - dotted = absorbed by (absorbed_by) - thin dotted "
        "from a ghost node = renamed.",
        "",
    ]
    return "\n".join(header) + "\n" + render_graph(manifests) + "\n"


def regenerate(vault, root=None, dry_run=False):
    """Full scan + render always run identically regardless of dry_run
    (spec 4.3: a --dry-run reports what WOULD land, never a partial
    analysis) - only the two atomic writes are skipped when dry_run."""
    ws_root = wslib.state_root(vault, root)
    manifests, orphans = wslib.discover_manifests(ws_root)
    problems = wslib.find_problems(manifests)

    index_path = os.path.join(ws_root, "index.md")
    graph_path = os.path.join(ws_root, "workstream-graph.md")

    wslib.atomic_write_lf(index_path, render_index(manifests, orphans, problems), dry_run=dry_run)
    wslib.atomic_write_lf(graph_path, render_graph_markdown(manifests), dry_run=dry_run)

    return {
        "manifests": len(manifests),
        "orphans": len(orphans),
        "problems": len(problems),
        "index_path": index_path,
        "graph_path": graph_path,
    }


def main(argv):
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace", newline="\n")

    p = argparse.ArgumentParser(prog="views.py")
    sub = p.add_subparsers(dest="cmd", required=True)
    p_regen = sub.add_parser("regen")
    p_regen.add_argument("--root", help="vault root override (default: cwd)")
    p_regen.add_argument("--dry-run", action="store_true", dest="dry_run")
    args = p.parse_args(argv)

    vault = os.path.abspath(args.root) if getattr(args, "root", None) else os.getcwd()

    if not wslib.looks_like_vault(vault):
        sys.stderr.write("views: refusing to run - %r has no staff/ directory "
                         "(does not look like a managed vault)\n" % vault)
        return 1

    try:
        summary = regenerate(vault, dry_run=args.dry_run)
    except OSError as e:
        sys.stderr.write("views: FAILED to write views: %r\n" % e)
        return 1

    verb = "would write" if args.dry_run else "->"
    print("views: %d manifest(s), %d orphan(s), %d anomaly(ies) %s %s, %s"
         % (summary["manifests"], summary["orphans"], summary["problems"], verb,
            os.path.relpath(summary["index_path"], vault).replace(os.sep, "/"),
            os.path.relpath(summary["graph_path"], vault).replace(os.sep, "/")))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except SystemExit:
        raise
    except BaseException as e:
        sys.stderr.write("views: crashed: %r\n" % e)
        sys.exit(1)
